### ISSUE TITLE
AudienceRestriction

### ISSUE THREAD

**Issue by S43534** [kingstarter/laravel-saml#1]
Hey,

great package! Just at the time when I needed it :-)

I am not familiar at all with SAML, but I had to make one change to make this package work (as IdP for Nextcloud SAML):

SAMLAuth, line 181
before
`new \LightSaml\Model\Assertion\AudienceRestriction([$authnRequest->getAssertionConsumerServiceURL()])`

after
`new \LightSaml\Model\Assertion\AudienceRestriction([$authnRequest->getIssuer()->getValue()])`

I don't know if that's a general issue or an issue related to Nextcloud. If it's not a general issue I would propose to make the audience restriction a value that is configurable (defaulting to the current value).

Best regards
Sebastian

**Comment by S43534** [comment]
Hey,

thanks for the answer!

It might well have to do with Nextcloud, I have strange effects there while other SPs work. 
Regarding the config value: 
`new \LightSaml\Model\Assertion\AudienceRestriction([config('new.config.value', $authnRequest->getAssertionConsumerServiceURL())])`
shouldn't break other apps as it defaults to the current value if the config value is not present.

But I will check the configuration and see if the error is there.

Sebastian

**Comment by steve-ks** [comment]
Good to know that this does not affect other SPs in your setting. Problem would be in case of using multiple SPs at once when having one overall config value. Even with a default setting this might break all SPs. I will think of a solution setting a specific SP value within the SP array, by this we could enable the config value for specific SPs only. I already tried something yesterday. I will push a solution as soon as it works.

**Comment by S43534** [comment]
Ah, got it. Great, thx!

**Comment by steve-ks** [comment]
Added Tag 1.0.1 with the bugfix. Tried everything, my SPs are not at all affected regardless of the new config value. Anyways debugging the SAMLResponse message showed that the audience restriction value is modified for specific SPs when using the config value. 

Could you please test if this works for your problem?

**Comment by S43534** [comment]
Sorry for not coming  back to you earlier.

It works just as intended - thx very much again!
