### ISSUE TITLE
 LightSaml \ Error \ LightSamlModelException NameID value not set

### ISSUE THREAD

**Issue by Awophil91** [kingstarter/laravel-saml#12]
I keep getting this error when using this package. Please help me out. In my Lravel 5.5 LoginController I invoked handleSamlLoginRequest() this way:
...

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;
    use SamlAuth;

    ...
    /**
     * The user has been authenticated.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();
        $this->clearLoginAttempts($request);

         $redirect_response = $this->response->redirectToIntended(
                $this->redirectPath(),302, [], $this->config->get('custom.app_secure'));

            if (!isset($request['SAMLRequest'])) {
                return $redirect_response;
            }

            //try {
            $this->handleSamlLoginRequest($request);
            //} catch (\Exception $e) { return $redirect_response; }

     }
    ...
}

**Comment by Awophil91** [comment]
Ok.

**Comment by xstoop** [comment]
https://github.com/kingstarter/laravel-saml/pull/11

see https://github.com/kingstarter/laravel-saml/blob/master/README.md

```
// OPTIONAL: Use to override the default email attribute to set a custom NameID value for a SP
// The NameID attribute must be a property on the User model.
'nameID' => 'username',
```

You need to change the nameID to Youself User model property

**Comment by AyodejiO** [comment]
I've done this, but no changes. Kindly help
