### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by forloops** [kingstarter/laravel-saml#8]
I attempted to install this in a fresh Laravel installation (v5.5.31) and ran into a problem when installing this via composer. 
```
composer require "kingstarter/laravel-saml":"dev-master"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for kingstarter/laravel-saml dev-master -> satisfiable by kingstarter/laravel-saml[dev-master].
    - Conclusion: remove symfony/event-dispatcher v4.0.3
    - Conclusion: don't install symfony/event-dispatcher v4.0.3
    - kingstarter/laravel-saml dev-master requires lightsaml/lightsaml ^1.3 -> satisfiable by lightsaml/lightsaml[1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - lightsaml/lightsaml 1.3.0 requires symfony/event-dispatcher ~2.3|~3.0 -
```
From the error, it looks like lightsaml/lightsaml needs to use symfony/event-dispatcher v3.x, but Laravel is now using symfony/event-dispatcher v4.0.3 .

**Comment by steve-ks** [comment]
I will check out on the problem soon. Sorry for the late response.

**Comment by vaggelis2018** [comment]
Same issue here, can't install it neither in laravel 5.5 or 5.6

**Comment by pushamaku** [comment]
Same issue. Anyone have a link to the fork with the patched version of lightsaml?

**Comment by vaggelis2018** [comment]
@pushamaku i think this is it
https://github.com/frostieDE/lightSAML

**Comment by pushamaku** [comment]
@vaggelis2018 Thank you for the link. I tried to install manually in vendor directory and update the autoloader files, but not sure how to actually install this package so it doesn't throw the error. Can you please share your solution if you got it to work?

**Comment by vaggelis2018** [comment]
This is what i did but to be sure i forked to mine repo
```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/frostieDE/lightSAML"
        }
    ],
    "require": {
        "php": ">=7.1.3",
        "fideloper/proxy": "~4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "~1.0",
        "lightsaml/lightsaml" : "dev-master"
    },
```

**Comment by steve-ks** [comment]
For the moment I've solved it similar to @vaggelis2018 by adding the frostieDE repo as vcs. Actually adding the VCS git repo should be enough as composer is selecting lightsaml 1.3.4 from frostieDE automatically, just tested it with a fresh laravel 5.6.3 installation. 

So actually this here is sufficient:
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/frostieDE/lightSAML"
        }
    ],
```
In case composer is still having problems adding the symfony4 lightsaml tag from frostieDE could help, tested it with a fresh laravel 5.5.34 installation and it worked as well. I would though not add in the lightsaml version by hand, letting composer select this automatically is way better.
```
    "require": {
        ... ,
        "lightsaml/lightsaml": "1.3.4"
    }
```

Sorry but that's all I can do here, hopefully Milos is pulling in [frostieDE's PR](https://github.com/lightSAML/lightSAML/pull/107) soon.
